#
#Version, do not change!##
#Range: > 0
Version = 3

#Small Ships Config:
[Ships]
	#
	#----Galley Speed Factor.----
	#	(takes effect after restart)
	#	default: 1.3
	#Range: 0.0 ~ 2.0
	GalleySpeedFactor = 1.3
	#
	#----Galley Turn Factor.----
	#	(takes effect after restart)
	#	default: 0.5
	#Range: 0.0 ~ 1.0
	GalleyTurnFactor = 0.5
	#
	#----Cog Speed Factor.----
	#	(takes effect after restart)
	#	default: 1.25
	#Range: 0.0 ~ 2.0
	CogSpeedFactor = 1.25
	#
	#----Cog Turn Factor.----
	#	(takes effect after restart)
	#	default: 0.1
	#Range: 0.0 ~ 1.0
	CogTurnFactor = 0.1
	#
	#----War Galley Speed Factor.----
	#	(takes effect after restart)
	#	default: 1.15
	#Range: 0.0 ~ 2.0
	WarGalleySpeedFactor = 1.15
	#
	#----War Galley Turn Factor.----
	#	(takes effect after restart)
	#	default: 0.4
	#Range: 0.0 ~ 1.0
	WarGalleyTurnFactor = 0.4
	#
	#----Drakkar Speed Factor.----
	#	(takes effect after restart)
	#	default: 1.25
	#Range: 0.0 ~ 2.0
	DrakkarSpeedFactor = 1.25
	#
	#----Drakkar Turn Factor.----
	#	(takes effect after restart)
	#	default: 0.3
	#Range: 0.0 ~ 1.0
	DrakkarTurnFactor = 0.3
	#
	#----Should Ships Make Swimming sounds?----
	#	(takes effect after restart)
	#	default: true
	PlaySwimmSound = true

